sudo: required
services:
  - docker

before_install:
  - docker build -t travistest -f Dockerfile.dev .

script:
  - docker run travistest npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-workflow-udemy"
  env: "DockerWorkflowUdemy-env"
  bucket_name: "elasticbeanstalk-us-east-1-426432506620"
  bucket_path: "docker-workflow-udemy"
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
  on:
    branch: master


